default:
  aws_access_key_id: 'AKIAICBFHQAOC6XMQDDQ'       # required
  aws_secret_access_key: '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'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'